#!/usr/bin/env python3
"""FAST-LIO's IMU-to-LiDAR extrinsic, from the URDF, as a ROS parameter file.

FAST-LIO wants the Avia LiDAR's pose in the Avia IMU's frame (mapping.extrinsic_T,
and mapping.extrinsic_R row-major: p_imu = R p_lidar + T). Both frames are in the
aircraft's TF tree: robot_description publishes avia_nominal_lidar_frame and its
child avia_imu_frame (the Livox factory offset) from /etc/uav/ros/description.yaml,
so a calibration written there reaches FAST-LIO at its next start, as it reaches
every other consumer of the geometry. uav-lio.service runs this before FAST-LIO;
the replay launcher runs it on the bag.

    lio_extrinsic.py --out FILE              # live: /tf_static from robot_state_publisher
    lio_extrinsic.py --bag BAG --out FILE    # a bag's recorded /tf_static

Bags recorded before avia_imu_frame existed (2026-10-06) do not have it; with --bag
the Livox factory offset stands in for it (LEGACY_IMU_IN_LIDAR) and the output says
so on stdout ("legacy"); --legacy-tf prints static_transform_publisher arguments for
that frame, which the replay launcher then publishes for the nodes that look it up.
"""
import argparse
import math
import os
import sys
import time

import numpy as np

# The Avia's built-in IMU in its LiDAR frame, axes aligned: Livox's factory offset (FAST-LIO's
# avia.yaml gives the LiDAR in the IMU frame, (0.04165, 0.02326, -0.0284)). Used only for bags
# that predate avia_imu_frame; the live value is robot_description's avia_imu_xyz.
LEGACY_IMU_IN_LIDAR = (-0.04165, -0.02326, 0.0284)


def quaternion_matrix(x, y, z, w):
    n = math.sqrt(x * x + y * y + z * z + w * w)
    x, y, z, w = x / n, y / n, z / n, w / n
    return np.array([[1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
                     [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
                     [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)]])


def matrix(rotation, translation):
    out = np.eye(4)
    out[:3, :3], out[:3, 3] = rotation, translation
    return out


class StaticTree:
    """The static TF tree: parent -> child edges as 4x4 matrices (child frame into parent)."""

    def __init__(self):
        self.parent = {}                          # child -> (parent, T_parent_child)

    def add(self, parent, child, translation, quaternion):
        self.parent[child.lstrip("/")] = (parent.lstrip("/"), matrix(quaternion_matrix(*quaternion), translation))

    def add_message(self, message):
        for t in message.transforms:
            tr, q = t.transform.translation, t.transform.rotation
            self.add(t.header.frame_id, t.child_frame_id, (tr.x, tr.y, tr.z), (q.x, q.y, q.z, q.w))

    def _to_root(self, frame):
        """T_root_frame and the root, following parents (at most 64 links)."""
        out = np.eye(4)
        for _ in range(64):
            if frame not in self.parent:
                return frame, out
            parent, edge = self.parent[frame]
            out = edge @ out
            frame = parent
        raise ValueError("TF loop")

    def has(self, frame):
        return frame in self.parent or any(p == frame for p, _ in self.parent.values())

    def lookup(self, target, source):
        """T_target_source (source-frame points into the target frame), or None if unconnected."""
        if not (self.has(target) and self.has(source)):
            return None
        root_t, t_root_target = self._to_root(target)
        root_s, t_root_source = self._to_root(source)
        if root_t != root_s:
            return None
        return np.linalg.inv(t_root_target) @ t_root_source


def extrinsic(tree, imu_frame, lidar_frame, allow_legacy=False):
    """(T, R row-major, legacy?) for FAST-LIO from the tree, or None. With allow_legacy (bags
    only), the factory IMU offset when the tree has the LiDAR frame but no IMU frame."""
    t_imu_lidar = tree.lookup(imu_frame, lidar_frame)
    legacy = False
    if t_imu_lidar is None:
        if not (allow_legacy and tree.has(lidar_frame)) or tree.has(imu_frame):
            return None
        t_imu_lidar = np.linalg.inv(matrix(np.eye(3), LEGACY_IMU_IN_LIDAR))
        legacy = True
    return [float(v) for v in t_imu_lidar[:3, 3]], [float(v) for v in t_imu_lidar[:3, :3].reshape(-1)], legacy


def render(t, r, source):
    fmt = lambda values: "[" + ", ".join(repr(round(v, 9)) for v in values) + "]"
    return (f"# Generated by lio_extrinsic.py: {source}\n"
            "/**:\n  ros__parameters:\n    mapping:\n"
            f"      extrinsic_T: {fmt(t)}\n      extrinsic_R: {fmt(r)}\n")


def write(path, text):
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write(text)
    os.replace(tmp, path)


def tree_from_bag(bag):
    from mcap.reader import make_reader
    from mcap_ros2.decoder import DecoderFactory
    paths = [bag] if os.path.isfile(bag) else sorted(os.path.join(bag, n) for n in os.listdir(bag) if n.endswith(".mcap"))
    tree = StaticTree()
    for path in paths:
        with open(path, "rb") as f:
            for _schema, _channel, _message, decoded in make_reader(f, decoder_factories=[DecoderFactory()]).iter_decoded_messages(topics=["/tf_static"]):
                tree.add_message(decoded)
    return tree


def tree_from_ros(timeout, imu_frame, lidar_frame):
    import rclpy
    from rclpy.qos import DurabilityPolicy, QoSProfile, ReliabilityPolicy
    from tf2_msgs.msg import TFMessage
    rclpy.init()
    node = rclpy.create_node("lio_extrinsic")
    tree = StaticTree()
    latched = QoSProfile(depth=100, durability=DurabilityPolicy.TRANSIENT_LOCAL, reliability=ReliabilityPolicy.RELIABLE)
    node.create_subscription(TFMessage, "/tf_static", tree.add_message, latched)
    end = time.monotonic() + timeout
    try:
        while time.monotonic() < end and tree.lookup(imu_frame, lidar_frame) is None:
            rclpy.spin_once(node, timeout_sec=0.5)
    finally:
        node.destroy_node()
        rclpy.shutdown()
    return tree


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default="", help="parameter file to write")
    ap.add_argument("--legacy-tf", action="store_true",
                    help="print static_transform_publisher arguments for the factory IMU frame and exit")
    ap.add_argument("--bag", default="", help="read /tf_static from this bag (directory or .mcap) instead of ROS")
    ap.add_argument("--imu-frame", default="avia_imu_frame")
    ap.add_argument("--lidar-frame", default="avia_nominal_lidar_frame")
    ap.add_argument("--timeout", type=float, default=60.0, help="live: seconds to wait for the frames")
    args = ap.parse_args()
    if args.legacy_tf:
        x, y, z = LEGACY_IMU_IN_LIDAR
        print(f"--x {x} --y {y} --z {z} --roll 0 --pitch 0 --yaw 0 --frame-id {args.lidar_frame} --child-frame-id {args.imu_frame}")
        return
    if not args.out:
        ap.error("--out is required")
    if args.bag:
        found = extrinsic(tree_from_bag(args.bag), args.imu_frame, args.lidar_frame, allow_legacy=True)
    else:       # live: the frame must exist; no stand-in on the aircraft
        found = extrinsic(tree_from_ros(args.timeout, args.imu_frame, args.lidar_frame), args.imu_frame, args.lidar_frame)
    if found is None:
        sys.exit(f"no transform {args.imu_frame} -> {args.lidar_frame} in /tf_static"
                 + (f" of {args.bag}" if args.bag else f" within {args.timeout:.0f} s (is uav-description running?)"))
    t, r, legacy = found
    source = (f"Livox factory IMU offset under {args.lidar_frame} (a bag from before {args.imu_frame})" if legacy
              else f"TF {args.imu_frame} -> {args.lidar_frame}" + (f" in {args.bag}" if args.bag else ""))
    write(args.out, render(t, r, source))
    print(("legacy " if legacy else "") + f"extrinsic_T {[round(v, 5) for v in t]} from {source}")


if __name__ == "__main__":
    main()
